[project]
name = "mixtex-ui"
version = "0.1.0"
description = "Package for MixTex UI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pyperclip>=1.9.0",
    "pystray>=0.19.5",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.1",
]
